### ISSUE TITLE
Question: Are interned strings freed when the interning StringInterner goes out of scope?

### ISSUE THREAD

**Issue by Diggsey** [Robbepop/string-interner#31]
The first thing I want to know about a string interner is whether it uses some kind of reference count to free symbols when they are no longer used, or if strings are just leaked (at least until the interner itself is freed).

**Comment by Robbepop** [comment]
The strings interned into an instance of `StringInterner` is always associated to the interner itself as it is the owning data structure. The strings that are passed out are not reference counted for performance reason and also it is pretty much not doable with the interface provided by the `StringInterner`. So yeah, strings "leak" if you intern them without using them at all. However, they can still be queried and used later. Some backends support interning of `&'static str` without overhead.
