### ISSUE TITLE
BucketBackend is not Send or Sync

### ISSUE THREAD

**Issue by mpdn** [Robbepop/string-interner#32]
Is there any reason for this?

I'm thinking it might be an oversight due to it using raw pointers and therefore needing to opt-in to those traits.

**Comment by Robbepop** [comment]
I think it should be `Send` and `Sync` so might be a bug, yes. Happy about a PR.

**Comment by mpdn** [comment]
Great! You'll probably see a PR from me then.

**Comment by mpdn** [comment]
Just discovered that `Send` and `Sync` actually is implemented for `BucketBackend` in this repo, it's just not in the crate on crates.io.

I'll just reference this repo directly, but it might be a good idea to push a new patch version to crates.

**Comment by Robbepop** [comment]
Release v0.12.1: https://crates.io/crates/string-interner/0.12.1

Closed.
