### ISSUE TITLE
Is this string interner supposed to be deterministic? 

### ISSUE THREAD

**Issue by vi** [Robbepop/string-interner#35]
Is it OK to store just the  `Symbol`s, forget the interner itself, then re-build the interner by feeding it the same strings in the same order, then use old symbols from previous interner?

This `type DefaultHashBuilder = RandomState;` looks suspicious.

Does determinism depend on which backend is in use?

---

Should the case when there is more than one interner (simultaneously or sequentelly) be documented more clearly?

**Comment by vi** [comment]
Experimented a bit and found out that `Symbol`s' `std::fmt::Debug`-printed numeric values seem to be consistent and even do not depend on the chosen backend.

**Comment by Robbepop** [comment]
The `StringInterner` is not deterministic by default as you have already found out.
However, when being fed the same strings in the same order it will produce the same mapping from `Symbol` to `String` always.

**Comment by Robbepop** [comment]
I close this as there have not been any further questions since my answer approx 2 months ago.
