### ISSUE TITLE
Trouble using with FNVHasher

### ISSUE THREAD

**Issue by ukutaht** [Robbepop/string-interner#4]
First of all, thanks for the library. I'm using this for a little compiler I'm writing. The default version works great, but I can't get it working with FNV hasher. Here's the error:

```
error[E0277]: the trait bound `*const str: std::marker::Send` is not satisfied in `string_interner::InternalStrRef`
  --> src/interner.rs:7:1
   |
7  | / lazy_static! {
8  | |     static ref INTERNER: RwLock<StringInterner<usize, FnvBuildHasher>> = {
9  | |         RwLock::new(StringInterner::with_hasher(FnvBuildHasher::default()))
10 | |     };
11 | |
12 | | }
   | |_^ `*const str` cannot be sent between threads safely
   |
   = help: within `string_interner::InternalStrRef`, the trait `std::marker::Send` is not implemented for `*const str`
   = note: required because it appears within the type `string_interner::InternalStrRef`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::collections::hash::table::RawTable<string_interner::InternalStrRef, usize>`
   = note: required because it appears within the type `std::collections::HashMap<string_interner::InternalStrRef, usize, std::hash::BuildHasherDefault<fnv::FnvHasher>>`
   = note: required because it appears within the type `string_interner::StringInterner<usize, std::hash::BuildHasherDefault<fnv::FnvHasher>>`
   = note: required because of the requirements on the impl of `std::marker::Sync` for `std::sync::RwLock<string_interner::StringInterner<usize, std::hash::BuildHasherDefault<fnv::FnvHasher>>>`
   = note: required by `lazy_static::lazy::Lazy`
   = note: this error originates in a macro outside of the current crate
```

I can create a minimal code sample to reproduce the error if needed. 

Here's the fnv hasher repo I'm using: https://github.com/servo/rust-fnv.

**Comment by Robbepop** [comment]
Thank you for reporting this issue.
This sounds strange to me because `StringInterner` does implement `Send` already but not all of its internal data structures (the `InternalStrRef` as stated in your error.). As can be seen here: https://github.com/Robbepop/string-interner/blob/master/src/lib.rs#L129
What version of String Interner do you use?
I will do some research about the problem in your report and see what I can do. :)

**Comment by ukutaht** [comment]
Ah sorry, I'm using `string-interner = "0.6.2"`

**Comment by Robbepop** [comment]
I am just confused, maybe we simply need to implement `Send` on `InternalStrRef`, too, to make everything work again but I am not so sure about this mechanic, so I want to ask first. :)

**Comment by Robbepop** [comment]
Okay I have found out what the problem is. I will fix it as soon as possible.

**Comment by ukutaht** [comment]
Thank you :)

**Comment by Robbepop** [comment]
Can you please verify that it is now working with v0.6.3?
Please not that v0.6.3 is not yet published on crates.io so you need to adjust the repo paths in your Cargo.toml.

**Comment by ukutaht** [comment]
Yes! Pointed to current master, it compiles and runs. Thank you!

**Comment by Robbepop** [comment]
Okay nice, so I will publish it to crates.io now as version 6.0.3 so you can build it normally again. :)
- Closed
