### ISSUE TITLE
Compare symbols by values of interned strings

### ISSUE THREAD

**Issue by AahzBrut** [Robbepop/string-interner#41]
Is it possible to add method to StringInterner, which will compare two symbols by theirs associated strings lexicographicaly?

**Comment by AahzBrut** [comment]
Yes, but for this i need to resolve both strings, which i'd rather not for brevity sake :) It will be just convenience method :)

**Comment by Robbepop** [comment]
What exactly differentiates "lexicographical" comparison from Rust's usual string comparison?
The cool thing about `StringInterner` symbols is that they are deduplicated which means that the same symbol always refers to the same string and different symbols always refer to strings that are different.
This means for string comparisons of interned strings it is enough to compare their symbols which is a very cheap operation.

**Comment by Robbepop** [comment]
> And I intern them in order - 2,3,1, will their symbols be like "symbol for 1" < "symbol for 2" < "symbol for 3"?

There currently is no guarantee given about that but the implementation of all current string interner backends would return symbols in the same order in which they have been interned so you'd end up with:

symbol(2) < symbol(3) < symbol(1) if you insert in the order 2, 3, 1.

**Comment by AahzBrut** [comment]
So it is as one would expect, but in my case i need to compare by string values, so "String 1" < "String 2" < "String 3" no matter in what order they were interned. And as I am using StringInterner behind RwLock (greatly multithreaded environment) its very convenient to me to minimize locking on it and if there is a method on StringInterner which will compare strings behind 2 symbols it will be very convenient to me :)

**Comment by Robbepop** [comment]
If you use the string interner in a heavily multithreaded environment you should definitely benchmark which string interner crate is the most efficient for you. For example there is the `lasso` crate that may be preferrable for multithreaded environments whereas this crate usually outperforms in single threaded environments.

**Comment by AahzBrut** [comment]
Ok, thanks, i will try.

вт, 18 янв. 2022 г., 13:27 Robin Freyler ***@***.***>:
