### ISSUE TITLE
*/+ confusion

### ISSUE THREAD

**Issue by reinerp** [Robbepop/string-interner#50]
https://github.com/Robbepop/string-interner/blob/95574e27c0cda19113ab27dc1e8a5f9f9fa5ab8a/src/backend/buffer.rs#L171

This `*` should probably be `+`?

**Comment by Robbepop** [comment]
yes, you are right this should be `+` instead of `*`. Feel free to file a PR to fix this. :)

**Comment by abs0luty** [comment]
We can close the issue i guess?
