### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by fornwall** [Robbepop/string-interner#62]
If possible, it would be nice with a new release to get the hashbrown update out, which fixes building with latest nightly (https://github.com/tkaitchuck/aHash/pull/183).

**Comment by Robbepop** [comment]
I wanted to release with this change https://github.com/Robbepop/string-interner/pull/51, but if it is urgent I can make a new `string-interner` release before that.

**Comment by fornwall** [comment]
Thanks! It's not urgent for us, we just switched to a git snapshot for now to fix the build with nightly rust.

**Comment by Robbepop** [comment]
@fornwall https://github.com/Robbepop/string-interner/pull/63
