### ISSUE TITLE
Implement From<usize> and Into<usize> for T: Symbol

### ISSUE THREAD

**Issue by artemshein** [Robbepop/string-interner#7]
Why from_usize and to_usize methods when there are fancy traits in std?

**Comment by Robbepop** [comment]
This is a design question.
I thought having concrete methods is less tricky to get right in very generic code. Although having `From<usize>` and `Into<usize>` trait impls would be more generic in another way.

**Comment by artemshein** [comment]
Why not have both?

**Comment by Robbepop** [comment]
The design of `Symbol` has changed in recent versions so this discussion is no longer really applicable.
