### ISSUE TITLE
Enabling the "std" feature always enables "serde"

### ISSUE THREAD

**Issue by davnavr** [Robbepop/string-interner#72]
The `"std"` feature for `string-interner` currently always enables `"serde"` when it is enabled, because [the `Cargo.toml` says](https://github.com/Robbepop/string-interner/blob/c2d9ad2099fb4f4dae0ebbc0575ca866aafcaec0/Cargo.toml#L32):
```toml
std = ["serde/std"]
```
instead of the correct:
```toml
std = ["serde?/std"]
```
which enables the `"std"` feature for `serde` **only when** `"serde"` is already enabled.

This currently means dependents of `string-interner` that set `default-features = false` while also enabling the `"std"` feature (expecting to only enable support for `std` *without* `serde`) may unknowingly depend on `serde`, taking a small amount of disk space (though I barely noticed any impact on compile times).

My current workaround is simply not enabling the `"std"` feature, and from my cursory glance of the source code, no code in `string-interner` itself currently uses anything from `std`, so this isn't too big of an issue.

**Comment by Robbepop** [comment]
Great catch! I was not aware of `std = ["serde?/std"]` syntax. Can you open a PR?

**Comment by Robbepop** [comment]
Fixed in #73.
